// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}},
{"name":"CustomGoldWindow","status":true,"description":"골드 윈도우 표시","parameters":{}},
{"name":"CustomMessageBox","status":true,"description":"메시지 박스 커스텀","parameters":{}},
{"name":"MapImage","status":false,"description":"맵상에 이미지 표시","parameters":{}},
{"name":"ShaderTest","status":false,"description":"쉐이더 공부","parameters":{}},
{"name":"Lighting","status":false,"description":"라이팅","parameters":{}},
{"name":"Outline","status":true,"description":"아웃라인","parameters":{}}
];
